services:
  db:
    image: mariadb:latest
    container_name: challenge3-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"  # Changed host port to 3307 to avoid conflicts
    volumes:
      - ./docker/db/init:/docker-entrypoint-initdb.d

  node-service:
    build: ./docker/api
    container_name: challenge3-node-service
    working_dir: /app
    volumes:
      - ./docker/api:/app
    command: npm start
    depends_on:
      - db
    environment:
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3000:3000"

  nginx:
    build: ./docker/nginx
    container_name: challenge3-nginx
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node-service

volumes:
  db_data: