version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: challenge4-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - ./docker/db/init:/docker-entrypoint-initdb.d

  node-service:
    build: ./docker/api
    # container_name: challenge4-node-service  # Remove or comment out this line
    working_dir: /app
    volumes:
      - ./docker/api:/app
    command: npm start
    depends_on:
      - db
    environment:
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    # Remove the ports section for node-service
    # ports:
    #   - "3000:3000"

  nginx:
    build: ./docker/nginx
    container_name: challenge4-nginx
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node-service

volumes:
  db_data: